### ISSUE TITLE
Documentation: import statement,object creation statement mentioned for `surrealdb.js'`  doesnot work

### ISSUE THREAD

**Issue by Divine1** [surrealdb/www.surrealdb.com#360]
### Description

below import statement,object creation statement mentioned for `surrealdb.js'`  doesnot work

```
import { Surreal } from 'surrealdb.js';
const db = new Surreal();
```

after checking the source code in `surrealdb.js'`, i modified tried below statement, it worked

```
import {ExperimentalSurrealHTTP} from 'surrealdb.js';
const db = new ExperimentalSurrealHTTP();
```
i'm using nodejs 18.17, typescript 5.1.3

please let me know if the documentation can be updated with this information

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ekwuno** [comment]
Hey @Divine1 can you give a bit more context. what was the error you were getting with the import statement.

**Comment by Divine1** [comment]
@Ekwuno 

below is the error when i use 
```
import { Surreal } from 'surrealdb.js';
const db = new Surreal();
```

```
TypeError: _WebSocket_node_js__WEBPACK_IMPORTED_MODULE_2__.default is not a constructor
    at open (webpack:///node_modules/surrealdb.js/esm/library/SurrealSocket.js:93:20)
    at <anonymous> (webpack:///node_modules/surrealdb.js/esm/strategies/websocket.js:86:27)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (webpack:///node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
    at _next (webpack:///node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:22:1)
    at executor (webpack:///node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:1)
    at constructor (webpack:///node_modules/zone.js/fesm2015/zone-node.js:1342:21)
    at <anonymous> (webpack:///node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:19:1)
    at connect (webpack:///node_modules/surrealdb.js/esm/strategies/websocket.js:87:27)
    at <anonymous> (webpack:///appserver/db/index.ts:14:12)
```

**Comment by Nash-x9** [comment]
Can document show environment info? like node version,etc. 

I had the same problem,
node v16.20.0
pnpm 8.6.6

> @Ekwuno
> 
> below is the error when i use
> 
> ```
> import { Surreal } from 'surrealdb.js';
> const db = new Surreal();
> ```
> 
> ```
> TypeError: _WebSocket_node_js__WEBPACK_IMPORTED_MODULE_2__.default is not a constructor
>     at open (webpack:///node_modules/surrealdb.js/esm/library/SurrealSocket.js:93:20)
>     at <anonymous> (webpack:///node_modules/surrealdb.js/esm/strategies/websocket.js:86:27)
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (webpack:///node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
>     at _next (webpack:///node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:22:1)
>     at executor (webpack:///node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:1)
>     at constructor (webpack:///node_modules/zone.js/fesm2015/zone-node.js:1342:21)
>     at <anonymous> (webpack:///node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:19:1)
>     at connect (webpack:///node_modules/surrealdb.js/esm/strategies/websocket.js:87:27)
>     at <anonymous> (webpack:///appserver/db/index.ts:14:12)
> ```

**Comment by Nash-x9** [comment]
I had resolve this question.
blow is my step to init project:

```
pnpm init
pnpm install surrealdb.node

#create app.js
touch app.js
```
app.js
```
const {Surreal} = require('surrealdb.node');

async function main() {
    try {
        const db = new Surreal();
        // connect to database server
        await db.connect('ws://127.0.0.1:8000');

        await db.signin({
            username: 'root',
            password: 'root'
        })
        await db.version().then(result=> {
            console.log(result)
        })
    } catch (e) {
        console.error('ERROR', e);
    }
}

main()
```
